### ISSUE TITLE
Python segfaults upon artwork loading

### ISSUE THREAD

**Issue by ghzgod** [linuxserver/docker-headphones#17]
So I've tried both versions of python within the nerdpack.  No matter what I do, I get

` python[24030]: segfault at 2b15695a9ff8 ip 00002b1560e558ba sp 00002b15695aa000 error 6 in libpython2.7.so.1.0[2b1560df3000+342000]`

This happens often upon settings changes but most often when adding a new artist.  After the segfault error, the headphones docker restarts itself.

**Comment by sparklyballs** [comment]
duplicate of #16
