### ISSUE TITLE
config.ini getting wiped when restarting container

### ISSUE THREAD

**Issue by peavers** [linuxserver/docker-headphones#18]
Container was built with:
```
docker create \
    --name=headphones \
    --restart=always \
    -v /home/ubuntu/docker/headphones:/config \
    -v /home/ubuntu/media/downloads:/downloads \
    -v /home/ubuntu/media/music:/music \
    -e PGID=1000 -e PUID=1000  \
    -e TZ=Pasific/Auckland \
    -p 8182:8181 \
    linuxserver/headphones
```
Making changes  to the config.ini on the host system (`/home/ubuntu/docker/headphones/config.ini`) are deleted when restarting the container. 

For example if I set a custom http_root (as per [here](https://github.com/rembo10/headphones/issues/15)) in the config and restart the container it's set back to `/` which is its default value.

**Comment by aptalca** [comment]
Try making the change when the container is stopped, and then start it

**Comment by sparklyballs** [comment]
stop the container, make your edits on the config.ini and restart the container.

i did this locally and changed the root to /headphones and then accessed the webui at `<my ip>:/8181/headphones`
