### ISSUE TITLE
Headphones has no rights to create folder in /music

### ISSUE THREAD

**Issue by peavers** [linuxserver/docker-headphones#19]
Container created with:
```
docker create \
    --name=headphones \
    --restart=always \
    -v /home/ubuntu/docker/headphones:/config \
    -v /home/ubuntu/media/downloads:/downloads \
    -v /home/ubuntu/media/music:/music \
    -e PGID=1000 -e PUID=1000  \
    -e TZ=Pasific/Auckland \
    -p 8182:8181 \
    linuxserver/headphones
```

Very similar issue as to https://github.com/linuxserver/docker-headphones/issues/8 but I'm not sharing anything over smb/cifs it's just a standard directory on the host. 

Accessing the container via bash I can create a new folder inside `/music` and gave it `0755` permissions which does allow headphones to process music but feels like a very dirty fix for the issue. 

I have a cluster of other containers built the same way with the same directories and it's only headphones that seems to have issues here.

**Comment by aptalca** [comment]
Is `/home/ubuntu/media/music` owned by the user with id 1000 in ubuntu?

**Comment by peavers** [comment]
Yeah it is.

**Comment by aptalca** [comment]
Does the owner have rwx ?

**Comment by peavers** [comment]
Sure does `drwxrwxr-x 2 ubuntu ubuntu 4096 Apr 16 02:24 music`

**Comment by aptalca** [comment]
Assuming ubuntu is user 1000, then that is exactly what headphones is running as, and should have the necessary permissions to write to that folder. Can you post a log with the errors?

And by the way, if you exec in and create folders, they will be owned by root. Keep that in mind.

**Comment by j0nnymoe** [comment]
I am assuming this is no longer an issue. If it is - please re-open this and we can look into it further.
Thanks.
