### ISSUE TITLE
Headphones does not support Python 3.x, image is not built from py2.7

### ISSUE THREAD

**Issue by Stealthii** [linuxserver/docker-headphones#30]
This is a general issue with the image, which is why I'm creating a new ticket.

The first line of the Headphones [Installation guide](https://github.com/rembo10/headphones/wiki/Installation) states that Python 2.6 or 2.7 is required to run the application, and that Python 3.x is not supported. This is backed up by evidence of some of the included libraries failing to work correctly, or causing the application to error, such as the older versions of [apscheduler](https://github.com/agronholm/apscheduler), [beets](https://pypi.python.org/pypi/beets), and [musicbrainzngs](https://github.com/alastair/python-musicbrainzngs).

I have tested running this application in a [simple Alpine image, with Python 2 and shntool available](https://github.com/Stealthii/docker-headphones/blob/master/Dockerfile#L8), which exhibits none of the crashing issues others are experiencing.

I'd suggest a rebase of this application to run atop a ls.io Python2 based image, to fix some of the long standing crashing issues, since your rebase to Alpine and Python 3.x [last year](https://github.com/linuxserver/docker-headphones/commit/09912ed66e74910a974a4e1cc85898f45a410e0b#diff-3254677a7917c6c01f55212f86c57fbf).

**Comment by sparklyballs** [comment]
image IS built from 2.7

docker run --rm=true -it linuxserver/headphones python -V

yields 

Python 2.7.14

**Comment by Stealthii** [comment]
This is indeed true for the latest image. I will check what happened, as when I tested this back last month I was ultimately sure that the image was running using Python 3.6 (the sole reason I tested a simple image of it instead).

I apologise for raising this ticket in a rush - I will verify the issue before commenting further.

**Comment by CHBMB** [comment]
You're confusing Alpine Linux version with python version
