### ISSUE TITLE
Hardcoded port

### ISSUE THREAD

**Issue by nightah** [linuxserver/docker-headphones#31]
Arch Linux
docker create --name headphones -v /mnt/NERV01/.config/.headphones:/config -v /mnt/NERV01:/downloads -e PUID=0 -e PGID=0 -p 8083:8083 -e TZ=Australia/Melbourne linuxserver/headphones

Currently in https://github.com/linuxserver/docker-headphones/blob/master/root/etc/services.d/headphones/run the port is hardcoded with -p 8181. This means that if you have already specified an alternative port in your configuration it will not be recognised.

If you do not map a config volume the default configuration is copied which already specifies port 8181. By removing the -p 8181 option it allows users with pre-configured ports to also function with this image.

**Comment by sparklyballs** [comment]
you just change the left hand side of the port assignment to anything you want keeping the right on 8181

as per instructions https://github.com/linuxserver/docker-headphones#parameters

**Comment by nightah** [comment]
I was aware that you could do that, just realised I didn't have to for both your sonarr and radarr docker images. Looks like some have the port hard coded (headphones, sabnzbd) whereas the above two do not.
