### ISSUE TITLE
Headphones force-bound to port 8181 

### ISSUE THREAD

**Issue by Slychocobo** [linuxserver/docker-headphones#33]
Headphones instance is hard-coded to use 8181, overwriting anything defined in the config.ini

**Docker Log output**
14-Jan-2018 19:41:21 - INFO :: MainThread : Using forced web server port: 8181
14-Jan-2018 19:41:21 - INFO :: MainThread : Starting Headphones web server on http://0.0.0.0:8181/

Source seems to be in the in the:  /run/s6/etc/services.d/headphones/run file caused by the -p 8181 argument.

exec \
        s6-setuidgid abc python /app/headphones/Headphones.py -p 8181 \
        --datadir=/config

Seems like this could be removed to allow a user-defined port-mapping.

**Comment by sparklyballs** [comment]
just use -`p xxxx:8181` in your run line replacing the xxxx's with your chosen port

**Comment by ghost** [comment]
Not an acceptable solution when running docker with macvlan network: `-p xxx:8181` is not available in this case.

**Comment by tobbenb** [comment]
If you use macvlan network the container have it's own IP and there are no conflicts with other apps using the same port.

**Comment by ghost** [comment]
Correct, all ports are available when using macvlan, without conflicting with either the host or the other macvlan'd instances.

I still don't understand how you get headphones to listen on port 80 when using macvlan though. Can you please elaborate?

**Comment by tobbenb** [comment]
I didn't say that you could run it on port 80. Why do you need to run it on port 80?
