### ISSUE TITLE
Missing dependancy

### ISSUE THREAD

**Issue by WolfieNuke** [linuxserver/docker-headphones#4]
Probably should add "shntool" to dependancies for headphones.

It's required to split single track albums.

I did "apt-get install shntool" post install, but it would be nice to add to the container by default.

Also should look into adding to installed path to config.ini (eg. "cue_split_shntool_path = /usr/bin/shntool")

See https://github.com/rembo10/headphones/issues/1938 for more info on topic.

**Comment by smdion** [comment]
I'll test out a build and update shortly.

**Comment by smdion** [comment]
Added
