### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by ikkeenjij36** [linuxserver/docker-headphones#48]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior

Getting the webui to start
## Current Behavior

404 not found page instead
If i look in the docker oversight the container is running
## Steps to Reproduce

1.New install on docker on synology box
2.
3.
4.

## Environment
**OS:**      
DSM 6.1.7-15284 Update 3
**CPU architecture:** x86_64/arm32/arm64      
**How docker service was installed:**      

## Command used to create docker container (run/create/compose/screenshot)

Using latest linuxserver io image/container in the docker application
## Docker logs

`-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/

Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    911
User gid:    911
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing...
[cont-init.d] 30-config: exited 0.
[cont-init.d] 99-custom-files: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
25-Jan-2020 13:53:15 - INFO :: MainThread : Checking to see if the database has                                                                                                                      all tables....
25-Jan-2020 13:53:31 - INFO :: MainThread : Retrieving latest version informatio                                                                                                                     n from GitHub
25-Jan-2020 13:53:31 - INFO :: MainThread : Headphones is up to date
25-Jan-2020 13:53:31 - INFO :: MainThread : Starting Headphones web server on ht                                                                                                                     tp://0.0.0.0:8181/
25-Jan-2020 13:53:32 - INFO :: MainThread : Scheduled background task: Search fo                                                                                                                     r Wanted
25-Jan-2020 13:53:32 - INFO :: MainThread : Scheduled background task: Download                                                                                                                      Scan
25-Jan-2020 13:53:32 - INFO :: MainThread : Scheduled background task: Library S                                                                                                                     can
25-Jan-2020 13:53:32 - INFO :: MainThread : Scheduled background task: MusicBrai                                                                                                                     nz Update
25-Jan-2020 13:53:32 - INFO :: MainThread : Scheduled background task: Check Git                                                                                                                     Hub for updates`

**Comment by CHBMB** [comment]
Not enough information to debug.  I suspect this is a support question not a bug.  Please use our forums or Discord
