### ISSUE TITLE
Can't connect to the database: disk I/O error

### ISSUE THREAD

**Issue by alebianco** [linuxserver/docker-headphones#5]
When sharing the config folder with a windows host, Headphones fails to connect to the database on startup and gives this log:

```
18-Dec-2015 00:44:09 - INFO :: MainThread : Checking to see if the database has all tables....
18-Dec-2015 00:44:09 - ERROR :: MainThread : Can't connect to the database: disk I/O error
18-Dec-2015 00:44:09 - INFO :: MainThread : Retrieving latest version information from GitHub
18-Dec-2015 00:44:09 - DEBUG :: MainThread : Requesting URL via GET method: https://api.github.com/repos/rembo10/headphones/commits/master
Dec 18 00:44:08 25df6913e9a3 syslog-ng[18]: syslog-ng starting up; version='3.5.3'
18-Dec-2015 00:44:09 - DEBUG :: MainThread : Latest version is 6720575bd94cda8ef153d4781c06dff2813975e0
18-Dec-2015 00:44:09 - INFO :: MainThread : You are running an unknown version of Headphones. Run the updater to identify your version
18-Dec-2015 00:44:09 - DEBUG :: MainThread : Using the following server values: MBHost: musicbrainz.org, MBPort: 80, Sleep Interval: 1
18-Dec-2015 00:44:09 - INFO :: MainThread : Using forced web server port: 8181
18-Dec-2015 00:44:09 - INFO :: MainThread : Starting Headphones web server on http://localhost:8181/
18-Dec-2015 00:44:09 - INFO :: MainThread : Scheduled background task: Search for Wanted
18-Dec-2015 00:44:10 - INFO :: MainThread : Scheduled background task: Download Scan
18-Dec-2015 00:44:10 - INFO :: MainThread : Scheduled background task: Library Scan
18-Dec-2015 00:44:10 - INFO :: MainThread : Scheduled background task: MusicBrainz Update
18-Dec-2015 00:44:10 - INFO :: MainThread : Scheduled background task: Check GitHub for updates
18-Dec-2015 00:44:10 - INFO :: MainThread : Scheduled background task: Torrent removal check
```

If i try to open the web ui, I either get a `GET http://192.168.99.100:8181/home net::ERR_CONNECTION_REFUSED` error, with no web content at all, or with this error message:

```
Traceback (most recent call last):
  File "/opt/headphones/lib/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/opt/headphones/lib/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/opt/headphones/lib/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/opt/headphones/headphones/webserve.py", line 72, in home
    myDB = db.DBConnection()
  File "/opt/headphones/headphones/db.py", line 50, in __init__
    self.connection.execute("PRAGMA synchronous = OFF")
OperationalError: disk I/O error
```

If the docker container is run without sharing the /config folder with the host, everything seems to work fine, but it's very much less desirable for portability.

**Comment by sparklyballs** [comment]
why are you sharing a docker config folder with a windows host ?
you're basically asking for trouble, permissions etc.

**Comment by alebianco** [comment]
well, because i do have a windows machine which i like to use and docker runs on linux, doesn't it?
also, permissions are not an issue, virtualbox does a pretty good job for that and i have a few other similar services running in docker sharing the same or similar folders without issues.

**Comment by sparklyballs** [comment]
permissions are everything in linux. linuxserver containers don't run as root by default, so probably does not have permissions to read/write to a mapped folder on a windows host. 
what is your docker create or run line ?

**Comment by alebianco** [comment]
here's folder permissions and process owner user and launch command

```
$ ls -l /config
total 74
drwxrwxrwx 1 headphones staff     0 Dec 18 00:42 cache
-rwxrwxrwx 1 headphones staff  5465 Dec 18 00:48 config.ini
-rwxrwxrwx 1 headphones staff 36864 Dec 18 00:43 headphones.db
-rwxrwxrwx 1 headphones staff 32768 Dec 18 01:40 headphones.db-shm
-rwxrwxrwx 1 headphones staff     0 Dec 18 00:43 headphones.db-wal
drwxrwxrwx 1 headphones staff     0 Dec 18 00:42 logs

$ ps aux | grep headphones
root        11  0.0  0.0    176     0 ?        Ss   01:40   0:00 runsv headphones
headpho+    15  1.6  3.6 717828 37332 ?        Sl   01:40   0:00 python /opt/headphones/Headphones.py --verbose -p 8181 --datadir=/config
```

I think i'll try to run the process as root next, but i'd really like to avoid it in general

**Comment by sparklyballs** [comment]
erm, are you sure that's our container ?

**Comment by sparklyballs** [comment]
```
root@Docker-Server:/# ls -l /config
total 60
drwxr-xr-x 2 abc abc  4096 Dec 18 01:50 cache
-rw-r--r-- 1 abc abc  5313 Dec 18 01:50 config.ini
-rw-r--r-- 1 abc abc 36864 Dec 18 01:55 headphones.db
drwxr-xr-x 2 abc abc  4096 Dec 18 01:50 logs
-rw-r--r-- 1 abc abc    40 Dec 18 01:50 version.lock
root@Docker-Server:/# ps aux | grep headphones
root       196  0.0  0.0    168     4 ?        Ss   01:50   0:00 runsv headphones
abc        201  0.3  1.2 1081472 44620 ?       Sl   01:50   0:01 python /app/headphones/Headphones.py -p 8181 --datadir=/config
root       242  0.0  0.0   8860   644 ?        S+   01:56   0:00 grep --color=auto headphones
```

**Comment by alebianco** [comment]
Sorry, I was trying to roll my own container (and i got the same error) and i mixed them up. Here's the revised info

```
ls -l /config
total 74
drwxrwxrwx 1 abc staff     0 Dec 18 00:42 cache
-rwxrwxrwx 1 abc staff  5465 Dec 18 02:11 config.ini
-rwxrwxrwx 1 abc staff 36864 Dec 18 00:43 headphones.db
-rwxrwxrwx 1 abc staff 32768 Dec 18 02:13 headphones.db-shm
-rwxrwxrwx 1 abc staff     0 Dec 18 00:43 headphones.db-wal
drwxrwxrwx 1 abc staff     0 Dec 18 00:42 logs
-rwxrwxrwx 1 abc staff    40 Dec 18 02:13 version.lock

ps aux | grep headphones
root       189  0.0  0.0    176     4 ?        Ss   02:13   0:00 runsv headphones
abc        193  2.2  4.6 745496 47256 ?        Sl   02:13   0:01 python /app/headphones/Headphones.py -p 8181 --datadir=/config

id abc
uid=1000(abc) gid=50(staff) groups=50(staff),100(users)
```

my shared volume comes owned by 1000:50 so i set those values for PGID and PUID

**Comment by sparklyballs** [comment]
your original post also seems to be referencing your own container 

"File "/opt/headphones/headphones/db.py", line 50, in **init**"

in place of /app/headphones

**Comment by alebianco** [comment]
the result is no different tho

```
Traceback (most recent call last):
  File "/app/headphones/lib/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/app/headphones/lib/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/app/headphones/lib/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/app/headphones/headphones/webserve.py", line 72, in home
    myDB = db.DBConnection()
  File "/app/headphones/headphones/db.py", line 50, in __init__
    self.connection.execute("PRAGMA synchronous = OFF")
OperationalError: disk I/O error
```

**Comment by sparklyballs** [comment]
are you trying to run both at the same time ?

**Comment by alebianco** [comment]
nope

```
$ docker ps -a
CONTAINER ID        IMAGE                           COMMAND             CREATED             STATUS                         PORTS                                              NAMES
5c87fe5ffb90        linuxserver/headphones:latest   "/sbin/my_init"     13 minutes ago      Up 12 minutes                  0.0.0.0:32770->8181/tcp                            headphones-2
a134ddb16829        usenet_sabnzbd                  "/sbin/my_init"     About an hour ago   Up About an hour               0.0.0.0:8080->8080/tcp                             sabnzbd
37fe48dd880e        usenet_deluge                   "/sbin/my_init"     About an hour ago   Up About an hour               0.0.0.0:8112->8112/tcp, 0.0.0.0:58846->58846/tcp   deluge
d4b8efd026da        usenet_couchpotato              "/sbin/my_init"     About an hour ago   Up About an hour               0.0.0.0:5050->5050/tcp                             couchpotato
aaf1fc6a793b        usenet_sickbeard                "/sbin/my_init"     About an hour ago   Up About an hour               0.0.0.0:8081->8081/tcp                             sickbeard
25df6913e9a3        usenet_headphones               "/sbin/my_init"     About an hour ago   Exited (0) 33 minutes ago                                                         headphones
3d2745bb41e5        phusion/baseimage:0.9.18        "/bin/true"         About an hour ago   Exited (0) About an hour ago                                                      storage
```

**Comment by sparklyballs** [comment]
it appears you've mapped port 32770 for headphones, so you can't access anything on port 8181, cos there isn't anything there.

**Comment by alebianco** [comment]
i was curl-ing from inside the container, from outside (on the right port) i get the `GET http://192.168.99.100:32770/home net::ERR_CONNECTION_REFUSEDD` without content

and

```
$ docker-machine ip default
192.168.99.100
```

**Comment by sparklyballs** [comment]
you've confused the hell out of me. 

first you post output from a completely different container, telling me you're getting no access on port 8181. 

i asked you for the run / create command and you give me the output of that container again rather than the run/create command.

then i see that you've mapped the container port to a different port on the host than the one you originally told me you tried to access.

the net result is i don't what to suggest because i am totally and utterly confused by the information you're giving me.

**Comment by alebianco** [comment]
i'm trying to provide all the info while doing a bunch of tryouts to compare results, yes, this is confusing for me as well.
i'd exclude a problem with the ports/network. highly unlikely.
volume permissions is more likely even if strange, given that other containers have no issues with the same setup.

could you tell me to which groups your abc user belongs to?

I'll try tomorrow to create/run the container from a osx machine and see if there's any difference

**Comment by sparklyballs** [comment]
it belongs to the users group inside the container, but it can be anything you like externally through the PGID and PUID (for user id) variables.

if you've been chopping and changing the same data between the two containers, you could have corrupted the database, have the wrong permissions for the linuxserver container to use the files.
post the docker create/run command, i have to sleep now, it's 3:30 am here.

the command i'm looking for will be something similar to this.

docker run -d --name=headphones .........

or docker create -d --name=headphones ........

**Comment by alebianco** [comment]
I finally manages to test from a OSX machines, which works ok.
I reset my docker machines to a clean state and tried to install the image on both OSX and Win with the same commands, keeping a log of all results: 
- [headphones-mac.txt](https://github.com/linuxserver/docker-headphones/files/69670/headphones-mac.txt)
- [headphones-win.txt](https://github.com/linuxserver/docker-headphones/files/69673/headphones-win.txt)

seems to me that the abc user is not the owner of the config folder. Let me know if you want me to try something next or if you need more info

**Comment by lonix** [comment]
Try changing the ovner to 911 on the Windows box ? IM not quizen sure how
that is done though
tir. 22. des. 2015 kl. 14.05 skrev Alessandro Bianco <
notifications@github.com>:

**Comment by alebianco** [comment]
not sure i can add/edit users like that on windows. for sure i don't have the useradd command available.
shouldn't specify the GUID/PUID values for the container have the same effect?

**Comment by alebianco** [comment]
So, found the source of the problem and a workaround but not the root cause yet. 

First, headphones uses 'localhost' as host name in the default cobfig: that makes it unreachable from outside the container. It has to be changed to 0.0.0.0 for it to work properly. 

Now for the disk error:
While checking the db from the console I noticed that by default it uses the WAL journaling option. I think the journal file my get locked for some reason and prevent any change to the db. 
Switching the journaling option in the config to OFF seems to solve the problem but exposes the db to a higher risk of corruption, not ideal in the long run. 

I'd like to understand why and how the journaling file gets locked but so far I had no luck. Any ideas? 

In general seems to be a problem related to sqlite3 and virtualbox volumes and not directly to this container, would be nice to have a disclaimer for Windows users,  especially if you were to choose to 'ignore' it

Thanks for your time
