### ISSUE TITLE
Change to develop fails

### ISSUE THREAD

**Issue by DoubtfulTurnip** [linuxserver/docker-headphones#50]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

Unable to change to develop branch

It would be really nice to have an option to choose the develop branch on container creation

------------------------------

## Expected Behavior
Setting config.ini to develop branch and restarting container. Container detects new updates and proceeds to update from develop branch.

## Current Behavior
Unable to update to develop branch. Errors displayed in log and failure to restart app correctly

## Steps to Reproduce
1. Shutdown container
2. Update config.ini to select develop (git options)
3. Start container
4. Click update in browser
5. Watch logs
6. Restarting container will start the app correctly again on the desired port with updates being available

## Environment

**CPU architecture:** x86_64    

## Docker logs

19-May-2020 21:47:05 - INFO :: CP Server Thread-4 : Retrieving latest version information from GitHub
19-May-2020 21:47:06 - INFO :: CP Server Thread-4 : Comparing currently installed version with latest GitHub version
19-May-2020 21:47:06 - INFO :: CP Server Thread-4 : New version is available. You are 3 commits behind
19-May-2020 21:47:42 - INFO :: MainThread : Received signal: update
19-May-2020 21:47:47 - INFO :: MainThread : Writing configuration to file
19-May-2020 21:47:47 - INFO :: MainThread : Headphones is updating...
19-May-2020 21:47:49 - ERROR :: MainThread : Git returned bad info. Are you sure this is a git installation?
19-May-2020 21:47:49 - ERROR :: MainThread : Couldn't download latest version
19-May-2020 21:47:49 - WARNING :: MainThread : Headphones failed to update: 'NoneType' object has no attribute 'split'. Restarting.
19-May-2020 21:47:49 - INFO :: MainThread : Headphones is restarting...
19-May-2020 21:47:49 - INFO :: MainThread : Restarting Headphones with ['/usr/bin/python', '/app/headphones/Headphones.py', '--datadir=/config', '--nolaunch']
19-May-2020 21:47:51 - INFO :: MainThread : Checking to see if the database has all tables....
19-May-2020 21:47:51 - INFO :: MainThread : Checking to see if the database has all tables....
19-May-2020 21:47:51 - INFO :: MainThread : Retrieving latest version information from GitHub
19-May-2020 21:47:51 - INFO :: MainThread : Retrieving latest version information from GitHub
19-May-2020 21:47:52 - INFO :: MainThread : Comparing currently installed version with latest GitHub version
19-May-2020 21:47:52 - INFO :: MainThread : Comparing currently installed version with latest GitHub version
19-May-2020 21:47:52 - INFO :: MainThread : New version is available. You are 3 commits behind
19-May-2020 21:47:52 - INFO :: MainThread : New version is available. You are 3 commits behind
19-May-2020 21:47:52 - INFO :: MainThread : Starting Headphones web server on http://0.0.0.0:8080/
19-May-2020 21:47:52 - INFO :: MainThread : Starting Headphones web server on http://0.0.0.0:8080/
19-May-2020 21:47:52 - INFO :: MainThread : Web server authentication is enabled, username is 'username'
19-May-2020 21:47:52 - INFO :: MainThread : Web server authentication is enabled, username is 'username'
19-May-2020 1:47:52 - ERROR :: HTTPServer Thread-1 : Uncaught exception: Traceback (most recent call last):
  File "/app/headphones/headphones/logger.py", line 214, in new_run
    old_run(*args, **kwargs)
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/app/headphones/lib/cherrypy/process/servers.py", line 205, in _start_http_thread
    self.httpserver.start()
  File "/app/headphones/lib/cherrypy/wsgiserver/wsgiserver2.py", line 1957, in start
    raise socket.error(msg)
error: No socket could be created -- (('0.0.0.0', 8080): [Errno 98] Address in use)
Traceback (most recent call last):
  File "/app/headphones/headphones/logger.py", line 214, in new_run
    old_run(*args, **kwargs)
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/app/headphones/lib/cherrypy/process/servers.py", line 205, in _start_http_thread
    self.httpserver.start()
  File "/app/headphones/lib/cherrypy/wsgiserver/wsgiserver2.py", line 1957, in start
    raise socket.error(msg)
socket.error: No socket could be created -- (('0.0.0.0', 8080): [Errno 98] Address in use)
Failed to start on port: 8080. Is something else running?

**Comment by tobbenb** [comment]
We don't support updating apps inside the container. 

As for builds using development branch I don't know if there are any plans to add it. The problem is that we don't really want to support a development branch as it might often have many pushes and/or bugs.

**Comment by DoubtfulTurnip** [comment]
Ah, no problem at all. I can understand the reasoning. If it makes any difference, right now, headphones' last develop branch update was 2 months ago, so I don't think it is something that will happen too often with this particular app. In the meantime, I will have a go at building this myself.

**Comment by dixonbg** [comment]
Currently, there is no support for qBittorrent API v2.0 on **master**. I guess, that's why @BuksheeTester opened this issue. 
https://github.com/rembo10/headphones/issues/3237#issuecomment-633752507
I am in the same boat, and I would be only able to use the develop branch. Can you add at least one build with tag **test** ? No support required :)
