### ISSUE TITLE
Headphones has no rights to create folder in /music

### ISSUE THREAD

**Issue by ghost** [linuxserver/docker-headphones#8]
Headphones has access to a folder mounted in `~/mounts/music` (mapped to `/music` for the container), but it is unable to create a directory in this folder.

When I access the container with `docker exec` I can create a folder in `/music` just fine. So it seems that the process isn't running as root in the container? I'm running into all kinds of permissions errors because of this. None of this has happened for me with the docker containers for couchpotato and sonarr for example.

**Comment by j0nnymoe** [comment]
Hi ismay,

Could you provide the full command you use to create this docker + any headphones logs showing permission errors?

Thanks

**Comment by lonix** [comment]
Aldo a note, no it does not run AS root. That is Kind of our thing. You should read the readme included in this repo

**Comment by ghost** [comment]
@lonix I did, it's just eluding why it wouldn't have permission to write in /music. I've been trying to figure this out for two weeks now and I keep running into permissions error with this docker when combined with cifs shares.

I'll post the requested info asap.

**Comment by ghost** [comment]
Ok, so I found out what the problem was. Since my `/music` folder is a mounted cifs share, headphones doesn't have permission to change file and folder permissions (since that should be done with sudo on that share I believe).

So that's what was causing the error. I'm now using beets to import my music, which doesn't cause these errors. Thanks for your replies!

**Comment by j0nnymoe** [comment]
@ismay Excellent, glad you managed to fix this.
